---

- name: Prepare
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Install required packages
      ansible.builtin.package:
        name:
          - httpd
          - initscripts
        state: present
